language: ruby
rvms:
    - 2.4.1
before_script:
    - nvm install 8.11.1
    - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.6.0
    - export PATH="$HOME/.yarn/bin:$PATH"
    - bundle install
    - yarn cache clean
    - yarn install
script:
    - yarn test
cache:
    yarn: true
    bundler: true
    directories:
        - node_modules
